# Generated by Django 5.0.4 on 2024-05-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chefs_eventscategory_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
